### ISSUE TITLE
Build failure: `System.IO.IOException: No space left on device`

### ISSUE THREAD

**Issue by jayagami** [bigbugcc/OpenWrts#44]
Building failed during the Compile step.

```

System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240703-031301-utc.log'

```

```

[build](https://github.com/jayagami/OpenWrts/actions/runs/9771275286/job/26973793376)
System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240703-031301-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240703-031301-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240703-031301-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)


```

**Comment by bigbugcc** [comment]
just only `No space left on device`, you could free space to build.

**Comment by jayagami** [comment]
> just only `No space left on device`, you could free space to build.

Thanks for replying.
I was building with GitHub Actions, so GitHub Actions is not available for building this project?
I noticed there is already a free step in the action steps.
I am trying to build it with a self-hosted action runner now.

**Comment by bigbugcc** [comment]
If you just want to compile your own firmware, please fork this project and modify the configurations in the `configs` directory and trigger the corresponding `action`. Do not modify the configuration files in workflow folder without understanding the `action` configuration parameters, which can cause problems with your compilation process.

**Comment by jayagami** [comment]
> If you just want to compile your own firmware, please fork this project and modify the configurations in the `configs` directory and trigger the corresponding `action`. Do not modify the configuration files in workflow folder without understanding the `action` configuration parameters, which can cause problems with your compilation process.

Thanks for your support. It's weird, but I re-forked this repo and successfully recompiled the firmware.
